name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2.0.1
      with:
        distribution: 'sdk-17'
        sdk-version: '30.0.3'  # Ensure this matches the version you need
    - name: Install build-tools
      run: sdkmanager "build-tools;29.0.3"
    - name: Add Android SDK to PATH
      run: echo "${ANDROID_HOME}/build-tools/29.0.3" >> $GITHUB_PATH

    - name: Grant execute permissions
      run: |
        chmod +x gradlew
        chmod +x alpha-bleed
        chmod +x alpha-bleeding-linux.exe

    - name: Build with Gradle
      run: ./gradlew alphableed buildDex

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: betamindy in a box
        path: build/libs/[!raw-]*.jar
