name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        distribution: 'adopt'

    # Gunakan cara yang lebih baru untuk setup Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: latest

    # Install komponen yang diperlukan menggunakan sdkmanager
    - name: Install Android SDK components
      run: |
        sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;30.0.3"
        yes | sdkmanager --licenses

    - name: Set Android SDK environment variables
      run: |
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/tools/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/build-tools/30.0.3" >> $GITHUB_PATH

    - name: Build with Gradle
      run: ./gradlew buildAll

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: betamindy in a box
        path: build/libs/[!raw-]*.jar
