name: Build Mindustry Mod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      

      - name: Build Desktop Mod
        run: |
          chmod +x gradlew
          ./gradlew desktop:jar
          mkdir -p artifact
          cp desktop/build/libs/desktop.jar artifact/my-mod-desktop.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: desktop-mod
          path: artifact/*.jar

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android Mod
        run: |
          chmod +x gradlew
          ./gradlew android:jar
          mkdir -p artifact
          cp android/build/libs/android.jar artifact/my-mod-android.jar

          # Konversi ke DEX (opsional)
          $ANDROID_HOME/build-tools/34.0.0/d8 artifact/my-mod-android.jar --output artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-mod
          path: artifact/*
